# Load required libraries
require("rvest")
require("stringr")
require("RMySQL")
require("zoo")
require("tidyr")
require("dplyr")
require("tm")
library(wordcloud2)
require("topicmodels")
require("wordcloud")
require("ggplot2")
require("afinn")
require("DT")
library(textstem)
library(yaml)
library(RMySQL)
library(tm)
library(topicmodels)
library(wordcloud)
require("sentimentr")
require("SentimentAnalysis")
library(RColorBrewer)
library(shiny)
library(DBI)
library(RMySQL)
library(tidyverse)  # For data manipulation
library(yaml)       # For reading YAML config file
library(shinycssloaders)
library(topicmodels)
library(tm)
library(textTinyR)
library(wordcloud)
library(RColorBrewer)
library(gridExtra)
library(tidytext)
library(dplyr)
library(plotly)

library(shiny)
library(DBI)
library(RMySQL)
library(glue)
